#!/bin/bash

x="_"
_dir=`pwd`
cd /usr/local/bin
files=`env ls $_dir`
sudo sh -c """ \
    for i in ${files}; do \
        if [[ '${i:0:1}' != '$x' ]]; then \
            echo $_dir/$i ; \
        fi \
    done;"""