#!/data/data/com.termux/files/usr/bin/bash

if [ $1 = "-h" ] || [ $1 = "--help" ]; then
    echo ""
    echo ""
    echo "  chroot_upon <mount dir> <option>"
    echo "  where:"
    echo "    <mount dir> is a mounted directory and chroot target"
    echo "        and"
    echo "    <option> is either 'm' or 'u'"
    echo "            where 'm' means mount additional components (for chroot)"
    echo "                and 'u' means unmount additional components."
    echo ""
    echo "  Examples:"
    echo ""
    echo "    ./chroot_upon /mnt m"
    echo ""
    echo "            (working in chroot environment,"
    echo "             then after exiting...)"
    echo ""
    echo "    ./chroot_upon /mnt u"
    echo ""
    echo ""
    exit 0
fi

MNT=$(echo "$1")

if [ $2 = "m" ]; then
    cp /etc/resolv.conf $MNT/etc/
    mount -t proc none $MNT/proc
    mount -t sysfs none $MNT/sys
    #mount -t devpts none $MNT/dev/pts
    mount -o bind /dev $MNT/dev
    mount -t devpts none $MNT/dev/pts
    LANG= chroot $MNT /bin/bash -c 'source /root/.bashenv; exec bash'
elif [ $2 = "u" ]; then
    cd /
    for i in /dev/pts /dev /sys /proc /sys
    do
	umount -lf $MNT/$i > /dev/null
    done
fi


