#!/bin/bash

# print version: cat /etc/issue
# copy resolv.conf (see linuxdeploy)
# umount based on /proc/mounts | grep $(pwd)

if [ $1 = "-h" ] || [ $1 = "--help" ]; then
    echo ""
    echo ""
    echo "  chroot_upon <mount dir> <option>"
    echo "  where:"
    echo "    <mount dir> is a mounted directory and chroot target"
    echo "        and"
    echo "    <option> is either 'm' or 'u'"
    echo "            where 'm' means mount additional components (for chroot)"
    echo "                and 'u' means unmount additional components."
    echo ""
    echo "  Examples:"
    echo ""
    echo "    ./chroot_upon /mnt m"
    echo ""
    echo "            (working in chroot environment,"
    echo "             then after exiting...)"
    echo ""
    echo "    ./chroot_upon /mnt u"
    echo ""
    echo ""
    exit 0
fi

MNT=$(echo "$1")

if [[ $2 = "m" ]]; then
	mount -t proc none $MNT/proc
	mount -t sysfs none $MNT/sys
	mount -t devpts none $MNT/dev/pts
	mount -o bind /dev $MNT/dev
	LANG= chroot $MNT /bin/bash
elif [[ $2 = "u" ]]; then
	cd /
	for i in $MNT/proc $MNT/sys $MNT/dev/pts $MNT/dev $MNT
	do
		umount $i
	done
fi


