#!/usr/local/bin/zsh

# [[ $1 = emacs ]]                                                                                    \
#     && which osascript > /dev/null 2>&1 && osascript -e 'tell application "Emacs" to activate'      \
#     || /Applications/Emacs.app/Contents/MacOS/bin/emacsclient -n -c "$@"

# [[ -z $EMACSCLIENT ]]       \
    # && _ec_client app

# fpath=$(realfullpath "$@")

# CMD=$(echo "$EMACSCLIENT -n -c $fpath")
# unset fpath

# echo "$CMD"
# eval "$CMD"

####################
#
# WORKING
#
#       ec -e '(org-open-link-from-string "[[~/.emacs.d/private/org/collections/android.org::#Org-074b9aab-d74a-472f-a14d-b96c05b05d77]]")' -e '(delete-other-windows)'
#
####################



ALL_ARGS=()
for arg in $@; do ALL_ARGS+=($arg); done

if [[ -z $PGSYSCONFDIR ]]; then
    set --
    INPUT=()
    pt=1
    for arg in $ALL_ARGS; do
        let pt=pt+1
        case "$arg" in

            "--eval" | "-e")
                set -- "$@" "-e";
                INPUT+=("-e");
                INPUT+=("'${ALL_ARGS[$pt]}'");
                ;;

            # "--help")   set -- "$@" "-H" ;;
            # *)         INPUT+=("$arg"); ;;

            *)          set -- "$@" "$arg"; #set -- "$NEW" "$arg";
                        ;;
        esac
    done
else
    INPUT=$@
fi

# OUT=">>/tmp/test"
# OUT=

# echo "\n\n" $OUT
# for it in $INPUT; do echo ">> $it <<" $OUT; done
# echo "@: $@" $OUT
# echo "INPUT: $INPUT" $OUT
# # echo "NEW: $NEW" $OUT
# echo "\n\n" $OUT

# return

source $HOME_ENV/.scripts/shell_env/shared/services/emacs

EMACS_DISPLAY=
if [[ $(uname -o) = Darwin ]]; then
    EXEC="/opt/local/bin/emacsclient"
    # EXEC="/Applications/Emacs.app/Contents/MacOS/bin/emacsclient"
    EMACS_SOCKET=$(e-get-x11-socket)
elif [[ $(uname -o) = GNU/Linux ]]; then
    EXEC="/usr/local/bin/emacsclient"
    # EMACS_DISPLAY="-d :51"
    # EMACS_SOCKET=$(e-get-protocol-socket)
    EMACS_SOCKET=$(e-get-x11-socket)
    # EMACS_SOCKET="/tmp/emacs1000/ub2-x11-server"
    #
    # /usr/local/bin/emacsclient -n -c -d :51 $@ -s /tmp/emacs1000/ub2-x11-server
    #
fi

# e-get-socket
# e-get-x11-socket
# e-get-protocol-socket

# EMACS_SOCKET=$(sudo lsof -U|grep emacs|grep unix|grep '/'|column -t | tr -s " "|cut -d ' ' -f8|sed -r 's/\s/\n/g'|uniq|grep x11|tail -n 1)
# EMACS_SOCKET_BAK=$(sudo lsof -U|grep emacs|grep unix|grep '/'|column -t | tr -s " "|cut -d ' ' -f8|sed -r 's/\s/\n/g'|head -n 1)

CMD="$EXEC -n -c $EMACS_DISPLAY $INPUT -s $EMACS_SOCKET"
# echo $CMD>>/tmp/test
[[ -n "$EMACS_SOCKET" ]]                        \
    && eval $CMD                                \
    || echo "emacsclient socket not found"
