#!/usr/bin/env python

import os
from subprocess                     import Popen                    as sub_popen
from subprocess                     import PIPE                     as sub_PIPE

def run_cmd(cmd):
    p = sub_popen(cmd,stdout=sub_PIPE,shell=True)
    (_out,_err) = p.communicate()
    assert _err is None
    return _out.rstrip('\n')

def growl(msg):
    growl = "/usr/local/bin/growlnotify --sticky --message '%s'"
    run_cmd(growl % msg)
    raise SystemExit

def _sublime(args):
    D = dict(zip(['prefix','user','dir','match'],args))
    D["fpath"] = D['match'] if os.path.isabs(D['match']) else os.path.join(D["dir"],D['match'])
    cmd = "/usr/local/bin/realfullpath %(prefix)s/%(user)s/%(fpath)s" % D
    cmd = cmd.replace('//','/')
    fpath = run_cmd(cmd)
    open_sublime = "/usr/local/bin/sublime_open %s" % fpath
    run_cmd(open_sublime)


if __name__ == '__main__':
    from sys import argv

    args = argv[1].strip('[]').split(',')
    args = [str(it).strip('"') for it in args]
    
    if args[0]=='sublime':
        _sublime(args[1:])
    else:
        print "Input:",argv
        print "Check file: %s" % __file__
