#!/usr/bin/env zsh

# THIS_DIR=${0:a:h}
THIS_FPATH=$0:A
THIS_DIR=$(dirname $THIS_FPATH)

if [[ -n $(uname -o|grep Linux) ]]; then
    [[ -n $(uname -m|grep aarch64) ]]   \
        && $THIS_DIR/_resources/ngrok-arm ${@:1}
    [[ -n $(uname -m|grep x86_64) ]]   \
        && $THIS_DIR/_resources/ngrok-linux ${@:1}
fi