#!/bin/bash

# gs      -sOutputFile="bw_$1" \
#         -dNOPAUSE -dBATCH -dSAFER \
#         -sDEVICE=pdfwrite \
#         -dCompatibilityLevel=1.3 \
#         -dPDFSETTINGS=/screen \
#         -dEmbedAllFonts=true \
#         -dSubsetFonts=true \
#         -sColorConversionStrategy=/Mono \
#         -sColorConversionStrategyForImages=/Mono \
#         -sProcessColorModel=/DeviceGray \
#         $1

gs \
    -sOutputFile="bw_$1.pdf" \
    -sDEVICE=pdfwrite \
    -sColorConversionStrategy=Gray \
    -dProcessColorModel=/DeviceGray \
    -dCompatibilityLevel=1.4 \
    -q \
    -dNOPAUSE \
    -dBATCH \
    $1