#!/data/data/com.termux/files/usr/bin/zsh

L="$1"
R="$2"

if [[ "${L:0:1}" = "/" ]]; then LOCAL="/Volumes/$USER$L"; else LOCAL="/Volumes/$USER$PWD/$1"; fi
if [[ "${R:0:1}" = "/" ]]; then REMOTE="/Volumes/$USER$R"; else REMOTE="/Volumes/$USER$PWD/$2"; fi

ssh admin -- /usr/local/bin/bcomp \"$LOCAL\" \"$REMOTE\"
