#!/bin/bash

[[ -n "$DEBUG_SHELL" ]] && echo "bash/_base"1$CLIENT_HOST && env|sort

#[[ -n "$SUDO_USER" ]] && export HOME_ENV=$(eval echo ~$SUDO_USER)
#[[ -z "$SUDO_USER" ]] && export HOME_ENV=$(eval echo ~$USER)

source $HOME_ENV/.scripts/shell_env/shell/bash/_env
[[ -n "$DEBUG_SHELL" ]] && echo "bash/_base_"3$CLIENT_HOST

case $- in
    *i*) ;;
      *) return;;
esac


[[ -n "$DEBUG_SHELL" ]] && echo "bash/_base_"4$CLIENT_HOST
source $HOME_ENV/.scripts/shell_env/_local

# if [[ -n "$BASH_VERSION" ]]; then
#     DIR="$HOME_ENV/.scripts/shell_env/bash/completers"
#     for i in `env find $DIR -maxdepth 1 -type f`; do source $i; done
# fi
