#!env zsh

if [[ -n $SSH_CONNECTION ]]; then
    CLIENT_IP=$(                    \
        echo "$SSH_CONNECTION"      \
        | cut -d ' ' -f1            \
        )
    SERVER_IP=$(                    \
        echo "$SSH_CONNECTION"      \
        | cut -d ' ' -f2            \
        | cut -d ' ' -f3            \
        )
    SERVER_PORT=$(                  \
        echo "$SSH_CONNECTION"      \
        | cut -d ' ' -f3            \
        )
else
fi

if [[   ($CLIENT_HOST = SERVER3)
    ||  ($CLIENT_IP = 10.0.0.53)
    ||  ($MACHINE_IP_INT = 10.0.0.53)
    ||  ($ITERM_SHELL = true)
    ]]; then

    [[ -n $DEBUG_SHELL ]] && echo "\n\tshared/2_iterm2 - sourcing\n"

    [[ -n $BASH_VERSION ]] && test -e "${HOME_ENV}/.iterm2_shell_integration.bash" && source "${HOME_ENV}/.iterm2_shell_integration.bash"
    [[ -n $ZSH_VERSION ]] && [[ -f "${HOME_ENV}/.iterm2_shell_integration.zsh" ]] && source "${HOME_ENV}/.iterm2_shell_integration.zsh"

    iterm_growl() { echo -e $'\e]9;'${1}'\007' ; return ; }
    export iterm2_hostname="$USER"
    iterm2_print_user_vars() {
        iterm2_set_user_var gitRepo $([[ -d .git ]] && basename `git rev-parse --show-toplevel`);
        iterm2_set_user_var gitBranch $([[ -d .git ]] && (git branch 2> /dev/null) | grep \* | cut -c3-);
        iterm2_set_user_var gitBranchTag $([[ -d .git ]] && [[ -n $(git tag) ]] && git describe --abbrev=0 --tags);

        [[ -n $MACHINE_DISPLAY_NAME ]]            \
            && _host="$MACHINE_DISPLAY_NAME"      \
            || _host="$USER"
        iterm2_set_user_var iterm2_host $_host;

        iterm2_set_user_var iterm2_addr $MACHINE_IP_INT;

    }
    alias it_user_profile="printf '\e]50;SetProfile=%s\007' $USER"

else
    [[ -n $DEBUG_SHELL ]] && echo "\n\tshared/2_iterm2 - NOT sourcing\n"
    return
fi


# load special functions and aliases if shell controlled by iTerm2
#if [ "$(( `printenv ITERM_PROFILE | wc -l` ))" -ne 0 ]; then
#    echo $'\e]50;SetProfile=$USER\007'
#fi
