#!/bin/zsh

setopt aliases

URL="http://info.sanspaper.com/sys/servers/s_idx/$SERVER_ID"

# JSON_1=$(printf '{"s_user":"%s","s_host":"%s"}' "$USER" "$(hostname)")
JSON_1=$(printf '{"s_host":"%s"}' "$(hostname)")
JSON_2=$(printf '{"home_env":"%s"}' "$HOME_ENV" )
JSON_3=$(printf '{"local_port":"%s"}' "$LOCAL_PORT")
JSON_4=$(printf '{"local_ip":"%s","ext_ip":"%s"}' "$(get_my_ip_int_f)" "$(get_my_ip_ext_f)")
JSON_5=$(printf '{"git_sync":%s}' "$LOCAL_GIT_SYNC")
JSON_6=$(printf '{"s_path":"%s"}' "$PATH")
JSONS=($JSON_1 $JSON_2 $JSON_3 $JSON_4 $JSON_5 $JSON_6)
a='{}'; for i in $JSONS; do a=$(jq -M -n -c "$a * $i"); done

echo $a #| curl -d @- $URL

# shell_env/_local
# shell_env/osx/services/osx_settings
# shell_env/shared/services/networking
# shell_env/shell/zsh/_base