#!env zsh

export HOME=/Users/admin

source /etc/environment

alias mp-android-dir="cd /opt/local/share/java/android-sdk-macosx/tools"

export ROOT_GRP=wheel
export SSHFS=/opt/local/bin/sshfs
export PGDATA=/opt/local/var/db/postgresql95/defaultdb/

# export IPY=$HOME_ENV/$SERVER/ipython
export WIKI=/Volumes/ub2/home/ub2/BD_Scripts/sethc23.github.io/_wiki

export ANDROID="/Users/admin/GIT_REPOS/Devices/Android"
export NEXUS="$ANDROID/NEXUS-6P"
export DROID="$ANDROID/scripts/.android"

# Git
#export GIT_CONFIG=$HOME_ENV/.git/config
#export GIT_CONFIG=$HOME_ENV/.gitconfig
#export GIT_TRACE=$HOME_ENV/.git/trace_log.txt
#source $SERV_HOME/.git/git-completion.bash
export HOMEBREW_GITHUB_API_TOKEN="49178d17dbb61624a7ccd9c542c7f258c1d4a01b"

# Amazon
#export EC2_HOME=/usr/local/ec2/ec2-api-tools-1.7.2.4
#export PATH=$PATH:/usr/local/aws:$EC2_HOME/bin
# export AWS_ACCESS_KEY=AKIAIBP2K5VUV7PUEG2A
# export AWS_SECRET_KEY=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
#export EC2_URL=https://ec2.us-east-1.amazonaws.com
#export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
export JAVA_HOME=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
# export AWS_CONFIG_FILE=$HOME_ENV/$SERVER/aws/.aws/config

#export PATH=$PATH:/Users/admin/bin/Sencha/Cmd/5.0.0.160
#export SENCHA_CMD_3_0_0="/Users/admin/bin/Sencha/Cmd/5.0.0.160"
#export ANDROID_HOME="/Users/admin/android/android-sdk"
#export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
#export PATH=$PATH:/Users/admin/votca
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/local/lib:/usr/lib64/openmpi/lib/

[[ -z "$(echo $PATH|grep term|grep cmd)" ]] \
    && export PATH=/Users/admin/.emacs.d/term-cmd:$PATH

if [[ -n $BASH_VERSION ]]; then
    if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
        source /opt/local/etc/profile.d/bash_completion.sh
    fi
fi
