#!env zsh


# f_kill_by() { sudo kill -9 `env ps -awx | grep $1 | grep -v grep | cut -d \  -f1`; }
# f_kill_by_port() { lsof -sTCP:LISTEN -T | awk '{print $2,$10}' | grep $1$ | cut -d " " -f1 | xargs -I '{}' kill -9 {} ; }

unalias locate_update
locate_update(){ \
    [[ ! -L "/usr/local/bin/updatedb" ]] &&
        sudo ln -nfs /usr/libexec/locate.updatedb /usr/local/bin/updatedb;
    sudo /opt/local/libexec/gnubin/updatedb; }
open_color_picker() { osascript -e 'tell application "Finder"' -e 'activate' -e 'choose color' -e 'end tell'; }
ps_cut(){ env ps -awwwx -o %cpu,%mem,start,etime,user,group,ppid,pid,tty,comm,args ${@:2} | cut -c -$(tput cols) ; }
ssh_f(){ \
    [[ -n "$(ls-mounts | grep "$1" | wc -l)" ]] && sudo umount -f /Volumes/$1 > /dev/null 2>&1;
    mkdir -p /Volumes/$1; sshfs $1:/ /Volumes/$1 -o follow_symlinks > /dev/null 2>&1;
    }
test_acro_js() {
    js_content="\
from appscript import app
app(u'Adobe Acrobat Pro').activate()
print app(u'Adobe Acrobat Pro').do_script(u\"\"\"";\
    js_file=$(cat /Volumes/ub2/home/ub2/gDrive/Reference/PDF/acrobat_js_test.js);\
    js_content=$(echo "$js_content$js_file")
    js_content="$js_content\"\"\");";\
    #echo "$js_content"; \
    echo "$js_content" > /tmp/test_acro_js.py;
    $HOME_ENV/.scripts/ENV/bin/python /tmp/test_acro_js.py ;\
    #rm -fr /tmp/test_acro_js.py; \
    }


alias ib_qt='$IPY/ENV/bin/ipython qtconsole --profile=nbserver --matplotlib=qt5 --pprint --autoindent --color-info --colors=linux --confirm-exit;'
alias ib_qt_here='/Users/admin/SERVER3/ipython/ENV/bin/ipython qtconsole --profile=nbserver --existing /Users/admin/.ipython/profile_nbserver/security/kernel-'
alias ls_mounts='df -h | tail -n +2 | cut -d \  -f1'
alias open_color_picker='open_color_picker_f'
alias ps-cpu='ps -r'
alias ps-mem='ps -m'
alias ps-threads='pstree'
alias ps='ps_cut ps'
alias pycharm='sudo /Applications/PyCharm.app/Contents/MacOS/pycharm'
alias rm='rmtrash'
alias rt_update_fw='cd $SERV_HOME/local_config/cisco && scp jffs/etc/config/fw.if cisco:/jffs/etc/config/ 2> /dev/null && rt_ /jffs/etc/config/fw.if 2> /dev/null'

alias subl='open -a "Sublime Text"'

alias ssh-psql='ssh -nNL localhost:8802:localhost:8800 ub2 &'
alias ssh-s1='dn_update_ip && dn_remote_tunnel open && ssh_f ub1'
alias ssh-s2='dn_update_ip && dn_remote_tunnel open && ssh_f ub2 && ssh-psql && env CLIENT_HOST=SERVER3 ssh ub2'
alias ssh-s6='dn_update_ip && dn_remote_tunnel open && ssh_f ub6'
alias ssh-s7='dn_update_ip && dn_remote_tunnel open && ssh_f ub7'
alias ssh-zero='ssh -nNR 8172:localhost:8172 ub2 &'

alias sudo_finder='sudo /System/Library/CoreServices/Finder.app/Contents/MacOS/Finder &'
alias sw_shell="sublime '/Users/admin/SERVER3/local_config/.sublime/Sublime Text 3/Packages/User/shell_env.sublime-workspace'"




