#!/bin/zsh

alias toggle_voiceover='osascript -e "`echo -e \"tell application \\"System Events\\"\ntell process \\"Finder\\"\nkey code 96 using command down\nend tell\nend tell\"`"'

# <<< --- OSX WIFI --- >>>
alias wifi_renew='sudo ipconfig set en1 DHCP'
alias wifi_hardware='networksetup -listallhardwareports'
alias wifi_off='networksetup -setairportpower en1 off'
alias wifi_on='networksetup -setairportpower en1 on'
alias wifi_scan='airport scan'
alias wifi_connect='networksetup -setairportnetwork en1'
alias wifi_disconnect='airport -z'
alias wifi_log_tail='tail -f /var/log/wifi.log'
alias wifi_bssid='airport-bssid en1'


# <<< --- SETTINGS --- >>>
alias disable_bt='echo "admin" | sudo defaults write /Library/Preferences/com.apple.Bluetooth.plist ControllerPowerState 0'
alias enable_bt='echo "admin" | sudo defaults write /Library/Preferences/com.apple.Bluetooth.plist ControllerPowerState 1'

alias disable_hidden='defaults write com.apple.finder AppleShowAllFiles -bool true; killall Finder'
alias enable_hidden='defaults write com.apple.finder AppleShowAllFiles -bool false; killall Finder'

alias enable_screen_share='sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -off -restart -agent -privs -all -allowAccessFor -allUsers -clientopts'

alias disable_lid='sudo nvram boot-args="niog=1"'
alias enable_lid='sudo nvram -d boot-args'

function enable_softwareupdate_f() { \
    sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.softwareupdated.plist;\
    sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.softwareupdate_download_service.plist; }
alias enable_softwareupdate='enable_softwareupdate_f'
function disable_softwareupdate_f() { \
    sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.softwareupdated.plist;\
    sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.softwareupdate_download_service.plist; }
alias disable_softwareupdate='disable_softwareupdate_f'

alias disable_ipv6='sudo networksetup -setv6off Ethernet && sudo networksetup -setv6off Wi-Fi'
alias enable_ipv6='sudo networksetup -setv6automatic Ethernet && sudo networksetup -setv6automatic Wi-Fi'

alias disable_spotlight='sudo mdutil -a -i off; sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist;'
alias enable_spotlight='sudo mdutil -a -i on; sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist;'

