#!env zsh

alias aws_addr='aws ec2 describe-addresses --filters Name="instance-id",Values="i-8206d068"'
alias aws_attach_volume='aws ec2 attach-volume --volume-id vol-349bc67f --instance-id i-8206d068 --device /dev/sdh'
alias aws_config='cat $AWS_CONFIG_FILE'
alias aws_create_snapshot='aws ec2 create-snapshot --volume-id vol-f4f5a9bc --description'
alias aws_create_volume='aws ec2 create-volume --snapshot-id snap-97e0dc1a --availability-zone us-east-1a'
alias aws_env='cd $SERV_HOME/aws; source ENV/bin/activate'
function aws_info_f() { aws ec2 describe-instances --filters Name="tag-value",Values="$1"; }
alias aws_info='aws_info_f'
alias aws_ip_assoc='aws ec2 associate-address --instance-id i-40b143ba --allocation-id eipalloc-44289721'
alias aws_ip_disassoc='aws ec2 disassociate-address --association-id eipassoc-5a8bc53e'
alias aws_owner_id='aws_info | grep IpOwnerId'
alias aws_s3_buckets='aws s3 ls'
alias aws_show_snapshots='aws ec2 describe-snapshots --filters Name="owner-id",Values="225385062148"'
alias aws_start='aws_env; aws ec2 start-instances --instance-id "i-8206d068"'