#!/bin/zsh

alias ports_listen='sudo lsof -n -i -P | grep LISTEN'
alias ports_listen_2='sudo netstat -ltnp'
alias ports_listen_3='nettop'
alias ports_sockets='netstat -lx'
alias ports_ssh='lsof -i tcp | grep ^ssh'

function net_dig_simple_f() { dig $1 +nostats +nocomments +nocmd; }
alias net_dig_simple='net_dig_simple_f'

function net_port_check_f(){
    nmap -p $1 $2
}
alias net_port_check='net_port_check_f'
alias net_port_check_help='echo "alias net_port_check <port> <ip/url>"'
alias net_route_v4='route -A inet'
alias net_route_v6='route -A inet6'

#arp -- address resolution protocol

# <<<   ---   DISTRIBUTED NETWORK (dn_*)   ---   >>>
alias dn_remote_tunnel_open="echo \"$(cat /etc/ssh/sshd_config | grep \^Port | cut -d \  -f2)\" | xargs -I '{}' ssh -nNR 1{}:localhost:{} ub2  > /dev/null 2>&1 &"
alias dn_remote_tunnel_close="echo '$(cat /etc/ssh/sshd_config | grep \^Port | cut -d \  -f2)' | xargs -I '{}' kill -9 `ps -awx | grep 1{} | grep -v grep | cut -d \  -f1` > /dev/null 2>&1"
alias dn_update_ip='curl -s -H "Content-Type: application/json" -X POST -d '\
"'"\
'{"local_addr":"'\
"$(get_my_ip_int)"\
'","ext_addr":"'\
"$(get_my_ip_ext)"\
'"}'\
"'"\
' --url "http://info.sanspaper.com/sys/servers/s_idx/$SERVER_ID"'