#!/bin/zsh

[[ -n "$DEBUG_SHELL" ]] && echo "_local_START"

if [[ -n $(uname -a | grep "Darwin") ]]; then
    MACHINE_ID=$(ifconfig -a|env grep -i ether|head -n 1|sed -E 's/(.*)(([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2}))(.*)/\2/g')    
else
    MACHINE_ID=$(ifconfig -a|env grep -i ether|head -n 1|sed -r 's/(.*)(([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2}))(.*)/\2/g')
fi

# ub1: 00:1b:63:bb:88:0b
# ub2: 2e:8a:82:38:77:3e 60:33:4b:97:84:a2
# admin: c8:2a:14:41:bf:23

if [[ "$MACHINE_ID" = "00:1b:63:bb:88:0b" || "$MACHINE_ID" = "2e:8a:82:38:77:3e" || "$MACHINE_ID" = "60:33:4b:97:84:a2" ]]; then

    [[ -n "$DEBUG_SHELL" ]] && echo "_local_ub2"

    if [[ -n "$ZSH_VERSION" ]]; then

        source $HOME_ENV/.scripts/shell_env/shell/zsh/_env 
        [[ -n "$DEBUG_SHELL" ]] && echo "shell_local"4$CLIENT_HOST

        autoload -U compinit && compinit
        autoload -U bashcompinit && bashcompinit

        [[ -n "$DEBUG_SHELL" ]] && echo "shell_local"5"$CLIENT_HOST"

        [[ "$CLIENT_HOST" = "SERVER3" ]] && export ZSH_THEME="cobalt2"
        [[ ! "$CLIENT_HOST" = "SERVER3" ]] && export ZSH_THEME="candy"

        plugins=$ZSH_PLUGINS
        # plugins+=(git-prompt)
        source $ZSH/oh-my-zsh.sh
        autoload -U compinit && compinit
        autoload -U bashcompinit && bashcompinit

        bindkey '\e[A' history-substring-search-up
        bindkey '\e[B' history-substring-search-down

        for i in `env find $HOME_ENV/.scripts/shell_env/shell/zsh/completers -maxdepth 1 -type f`; do source $i; done

    fi

    local_port=9092
    git_sync=[{"/home/ub2/.scripts":"git@github.com:sethc23/shared_scripts.git"}]

    [[ -n "$DEBUG_SHELL" ]] && echo "_local"6"$CLIENT_HOST"
    # source_files_and_sub_dirs "$BASE_DIR/shared"
    # echo "shell_local"7"$CLIENT_HOST"
    _env=$(uname -a)
    [[ -n $(echo $_env | grep "Linux") ]] && \
        source_files_and_sub_dirs "$HOME_ENV/.scripts/shell_env/shared" && \
        source_files_and_sub_dirs "$HOME_ENV/.scripts/shell_env/linux"

    [[ -n "$DEBUG_SHELL" ]] && echo "_local"8"$CLIENT_HOST"
    source_files "$HOME_ENV/.scripts/shell_env/shell"
    [[ -n "$DEBUG_SHELL" ]] && echo "_local"5$CLIENT_HOST

elif [[ "$MACHINE_ID" = "c8:2a:14:41:bf:23" ]]; then

    [[ -n "$DEBUG_SHELL" ]] && echo "_local_admin"

    if [[ -n "$ZSH_VERSION" ]]; then

        source $HOME_ENV/.scripts/shell_env/shell/zsh/_env 
        [[ -n "$DEBUG_SHELL" ]] && echo "_local_admin_2"

        autoload -U compinit && compinit
        autoload -U bashcompinit && bashcompinit

        export ZSH_THEME="cobalt2"
        plugins=$ZSH_PLUGINS
        plugins+=(osx)
        source $ZSH/oh-my-zsh.sh
        compinit

        bindkey '\e[A' history-substring-search-up
        bindkey '\e[B' history-substring-search-down

        for i in `env find $HOME_ENV/.scripts/shell_env/shell/zsh/completers -maxdepth 1 -type f`; do source $i; done

        # eval "$(register-python-argcomplete /home/ub2/.scripts/syscontrol/sys_control.py)"
      
    fi

    local_port=9093
    git_sync=[{"/Users/admin/.scripts":"git@github.com:sethc23/shared_scripts.git"}]

    source_files_and_sub_dirs "$HOME_ENV/.scripts/shell_env/shared"
    source_files_and_sub_dirs "$HOME_ENV/.scripts/shell_env/osx"
    source_files "$HOME_ENV/.scripts/shell_env/shell"

    #source_files "$HOME_ENV/.scripts/shell_env/shell"
    #[[ -n $(echo $_env | grep "Darwin") ]] && source_files_and_sub_dirs "$BASE_DIR/osx"
    #source_files_and_sub_dirs "$BASE_DIR/shared"

    [[ -n "$DEBUG_SHELL" ]] && echo $PATH

fi

if [[ "$PROFILE_STARTUP" == true ]]; then
    unsetopt xtrace
    exec 2>&3 3>&-
fi
[[ $START_TMUX = true ]] && tmux attach -t base || tmux new -s base