#!env zsh

[[ -n "$DEBUG_SHELL" ]] && echo "linux/linux_vars"

export ROOT_GRP=root
export SSHFS=/usr/bin/sshfs

export IPY=$SERV_HOME/ipy_jupyter/notebooks
#export PYTHONPATH=$IPY/scripts/startup.py

export PKG_CONFIG_PATH=/usr/lib/pkgconfig/:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/rsyslog/



# ---------------------------------------
# Git
#export GIT_CONFIG=$HOME/.gitconfig
#export GIT_TRACE=$HOME/.git/trace_log.txt

# ---------------------------------------
# Amazon
# export EC2_HOME=/usr/local/ec2/ec2-api-tools-1.7.2.4
# export PATH=/usr/local/aws:$EC2_HOME/bin:$PATH
# export AWS_ACCESS_KEY=AKIAIBP2K5VUV7PUEG2A
# export AWS_SECRET_KEY=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
# export EC2_URL=https://ec2.us-east-1.amazonaws.com
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export AWS_HOME=$SERV_HOME/aws
export AWS_CONFIG_FILE=$AWS_HOME/.aws/config

# ---------------------------------------
# RabbitMQ
#export RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.config
#export RABBITMQ_PID_FILE=$SERV_HOME/run/pids/sv_rabbitmq.pid
#export RABBITMQ_NODENAME="$USER@$HOST"
#export RABBITMQ_SERVER_START_ARGS="--port=15672 --username=ub2 --password=mq_money --format=pretty_json"

# ---------------------------------------
# RVM
# export PATH="$PATH:$HOME_ENV/.rvm/bin"

#<<<<<-------------------------------<<<<

