#!/bin/zsh

aporo_env() {              source $APORO/ENV/bin/activate; }
aporo() {                  cd $APORO; aporo_env; }
aporo_ib() {               aporo; ipython; }
backup_pgsql(){
    SRC_PATH="/var/lib/postgresql/9.5"
    IMG_NAME="pgsql9.5_fs"
    MOUNT="/mnt/tmp"

    d-compress $SRC_PATH /tmp/$IMG_NAME.img;
    sudo mkfs.ext4 /tmp/$IMG_NAME.img;
    sudo mkdir -p $MOUNT;
    sudo mount -t ext4 -o loop /tmp/$IMG_NAME.img $MOUNT;
    sudo cp -ar $SRC_PATH $MOUNT/
    sudo umount $MOUNT
    }
d-compress(){
    SRC_PATH=$1
    IMG_PATH=$2
    DEFAULT_SAVE_FPATH="/tmp/d-compressed.gz";
    [[ -n $IMG_PATH ]] && DEFAULT_SAVE_FPATH=$IMG_PATH;
    DIR_SIZE=$(sudo du -s $SRC_PATH|cut -f1);
    IMG_SIZE=$(python -c "print int(round((($DIR_SIZE*0.20)+$DIR_SIZE)/1000.0,0))");
    [[ -n $IMG_PATH ]] && DEFAULT_SAVE_FPATH=$IMG_PATH;
    dd if=/dev/zero of=$DEFAULT_SAVE_FPATH bs=1M count=$IMG_SIZE;
    }
ib_konnect() {             sudo $IPY/ENV/bin/ipython console --existing \
    $HOME/.ipython/profile_default/security/kernel-$1.json; kill $1;
    }
path_of_pid_f() { readlink -f /proc/$1/exe; }
newalias_linux() {         echo "alias "$1 >> $HOME/.alias_linux; source_bash; push_linux_aliases; }

# f_kill_by() {              sudo kill -9 `ps -ef | grep $1 | awk '{print $2}'`; }
# alias kill_by='f_kill_by'
    
alias blog_serv_local='github-pages check-health && bundle update && bundle exec jekyll serve --baseurl "" --port 4000'
alias BT_off='sudo /etc/init.d/bluetooth stop'
alias BT_on='sudo /etc/init.d/bluetooth start'
alias BT_restart='sudo /etc/init.d/bluetooth restart'
alias cel_env='cd $SERV_HOME/aprinto; source ENV/bin/activate'
alias chk_filesystem_types='sudo blkid'
alias chkconfig='sudo sysv-rc-conf'
alias disable_wifi='sudo ifconfig wlan0 down'
alias dns_update='$SERV_HOME/dns/godaddy.py'
alias email='mutt -a /tmp/backup.xml -s "tasker" -- seth.t.chase@gmail.com'
alias locate_update='sudo /usr/bin/updatedb'
alias mail_old='mail -f $HOME_ENV/mbox'
alias path_of_pid='path_of_pid_f'
alias ps-command='ps --sort=comm'
alias ps-cpu='ps --sort=+%cpu'
alias ps-latest='ps --sort=-etime'
alias ps-mem='ps --sort=+%mem'
alias ps-pid='ps --sort=+ppid,+pid'
alias ps-threads='ps -f --sort=+ppid,+pid'
alias pydoc='python -m pydoc'
alias red_keys='redis-cli -h localhost -p 6379 -n 0 keys \*'
alias S='kill_by syslog-ng; printf "" | printf "Checking processes..." | ps -A | grep syslog-ng | grep -v grep; sl_push_config; sudo syslog-ng;'
alias scr_ed='scr_env; cd $HOME/.scripts'
alias scr_env='source $HOME/.scripts/ENV/bin/activate'
alias semacs='sudo emacs -nw'
alias show_temp='sensors'
alias topcpu='env ps -wx -o pid=PID,%cpu=CPU,%mem=MEM,comm=CMD | head -15'
alias uuid=uuid_random
alias uuid_random='uuidgen -r'
alias uuid_time='uuidgen -t'
alias vi='vim'