#!/bin/zsh

function newalias_linux() {         echo "alias "$1 >> $HOME/.alias_linux; source_bash; push_linux_aliases; }
function ib_konnect() {             sudo $IPY/ENV/bin/ipython console --existing \
    $HOME/.ipython/profile_default/security/kernel-$1.json; kill $1;}

alias scr_env='source $HOME/.scripts/ENV/bin/activate'
alias scr_ed='scr_env; cd $HOME/.scripts'

function aporo_env() {              source $APORO/ENV/bin/activate; }
function aporo() {                  cd $APORO; aporo_env; }
function aporo_ib() {               aporo; ipython; }


alias BT_off='sudo /etc/init.d/bluetooth stop'
alias BT_on='sudo /etc/init.d/bluetooth start'
alias BT_restart='sudo /etc/init.d/bluetooth restart'

function path_of_pid_f() { readlink -f /proc/$1/exe; }
alias path_of_pid='path_of_pid_f'
alias chk_filesystem_types='sudo blkid'
alias emacs='emacs -nw'
alias semacs='sudo emacs -nw'

alias jupyter_nbconvert='jupyter-nbconvert --to=notebook --nbformat=3 --inplace /home/ub2/SERVER2/ipython/notebooks/'

alias ipt='sudo iptables -nL -v'
alias ipt_flush='sudo iptables -F'
alias ipt_nat='sudo iptables -t nat -nL -v'
alias ipt_nat_flush='sudo iptables -t nat -F'
alias ipt_proxy='sudo iptables -t nat -I OUTPUT 1 -o eth0 -m owner \! --gid-owner 1003 -p tcp --match multiport --dports 80,443 -j REDIRECT --to-port 10052'
alias ipt_proxy_2='sudo iptables -t nat -I PREROUTING 1 -o eth0 -m owner \! --gid-owner 1003 -p tcp --match multiport --dports 80,443 -j REDIRECT --to-port 10052'


function m_proxy_eth() { \
    ipt_flush; \
    ipt_nat_flush; \
    sudo iptables -t nat -I OUTPUT -o eth0 -p tcp -m owner \! --uid-owner mitmproxy --dport 80 -j REDIRECT --to-port 10052; \
    sudo iptables -t nat -I OUTPUT -o eth0 -p tcp -m owner \! --uid-owner mitmproxy --dport 443 -j REDIRECT --to-port 10052; \
    sudo -u mitmproxy mitmweb --transparent -wport=11152 --wiface=eth0 --wfile=mitm_res.out --wdebug --port 10052 && sudo iptables -t nat -F;
}

function m_proxy_tun() { \
    ipt_flush; \
    ipt_nat_flush; \
    sudo iptables -t nat -I OUTPUT 1 -o tun0 -m owner \! --uid-owner mitmproxy -p tcp --dport 80 -j REDIRECT --to-port 10052; \
    sudo iptables -t nat -I OUTPUT 1 -o tun0 -m owner \! --uid-owner mitmproxy -p tcp --dport 443 -j REDIRECT --to-port 10052; \
    #sudo -u mitmproxy mitmproxy --transparent --port 10052 --eventlog --intercept '.*' && sudo iptables -t nat -F; \
    sudo -u mitmproxy mitmweb --transparent -wport=11152 --wiface=eth0 --wfile=mitm_res.out --wdebug --port 10052 && sudo iptables -t nat -F;
}

function f_kill_by() {              sudo kill -9 `ps -ef | grep $1 | awk '{print $2}'`; }
alias kill_by='f_kill_by'

alias mail_old='mail -f ~/mbox'

alias locate_update='sudo /usr/bin/updatedb'
alias ls='ls --color --almost-all --classify --human-readable --ignore-backups --format=verbose --indicator-style=file-type --indicator-style=slash'
#alias ls='ls --almost-all --human-readable --ignore-backups --format=verbose --indicator-style=file-type --indicator-style=slash | LC_COLLATE=C sort -k9,9 --ignore-case'
alias red_keys='redis-cli -h localhost -p 6379 -n 0 keys \*'

alias cel_env='cd $SERV_HOME/aprinto; source ENV/bin/activate'

alias ports_listen='sudo lsof -n -i -P | grep LISTEN'
alias ports_listen_2='sudo netstat -ltnp'
alias ps='ps -ef'
alias pydoc='python -m pydoc'
alias show_temp='sensors'
alias uuid_random='uuidgen -r'
alias uuid_time='uuidgen -t'
alias uuid=uuid_random
alias S='kill_by syslog-ng; printf "" | printf "Checking processes..." | ps -A | grep syslog-ng | grep -v grep; sl_push_config; sudo syslog-ng;'
alias topcpu='env ps -wx -o pid=PID,%cpu=CPU,%mem=MEM,comm=CMD | head -15'
alias vi='vim'

alias chkconfig='sudo sysv-rc-conf'
alias email='mutt -a /tmp/backup.xml -s "tasker" -- seth.t.chase@gmail.com'
alias dns_update='$SERV_HOME/dns/godaddy.py'
alias disable_wifi='sudo ifconfig wlan0 down'

alias blog_serv_local='github-pages check-health && bundle update && bundle exec jekyll serve --baseurl "" --port 4000'
