#!/bin/zsh

[[ -n "$DEBUG_SHELL" ]] && echo "_shared_"

assign() {  eval "$1=\$(cat; echo .); $1=\${$1%.}";}
cde_f() {
    if [[ -z $1 ]]; then
        if [[ -z `env ls | env grep ENV` ]]; then
            echo "No virtualenv ENV"
        else
            source ENV/bin/activate
        fi
    else
        if [[ -z `env ls $1 | env grep ENV` ]]; then
            echo "No virtualenv ENV"
        else
            cd $1
            source ENV/bin/activate
        fi
    fi
    }
copy_back_aliases() { cp -R $HOME_ENV/.alias_shared $HOME_ENV/.scripts/.alias_shared; }
diff_dir_all() { colordiff --brief --recursive $1 $2; }
diff_dir_left() { colordiff --brief --recursive $1 $2 | grep "Only in $(echo $1 | sed 's/[^/]*$//')"; }
diff_dir_right() { colordiff --brief --recursive $1 $2 | grep "Only in $(echo $2 | sed 's/[^/]*$//')"; }
diff_dir_right_copy_left() { 
    here=$(echo $(pwd))
    f=$(diff_dir_right $1 $2 | awk '{print $3$4}' | sed 's/:/\//g' | sed 's/\/\//\//g');
    repl_part=$(echo $2 | sed 's/\//\\\//g');
    for from_file in $f 
        do
            to_file=$(echo $1$from_file | sed "s/$repl_part//g")
            cmd=$(echo "cp -R "$here/$from_file $to_file)
            #cmd=$(echo $here/$from_file $to_file)
            
            sh -c "$cmd"
            
            # | xargs cp -R
            #cp -R $(echo $from_file $to_file)
        done;
    unset here f repl_part to_file;}
diff_dir_files() { colordiff --brief --recursive $1 $2 | grep -E '^Files'; }
diff_dir_same() { colordiff --brief --recursive --report-identical-files $1 $2 | grep 'are identical'; }
diff_files() { colordiff --side-by-side --suppress-common-lines --ignore-all-space \
    --ignore-blank-lines --ignore-space-change --ignore-blank-lines --width=200 $1 $2; \
    }
diff_files_left() { colordiff --side-by-side --suppress-common-lines --ignore-all-space \
    --ignore-blank-lines --ignore-space-change --ignore-blank-lines --width=200 $1 $2 | \
    awk 'NR==1{print} NR>1 && /[^a-zA-Z0-9]<[^a-zA-Z0-9]/ {print}'; \
    }
diff_files_right() { colordiff --side-by-side --suppress-common-lines --ignore-all-space \
    --ignore-blank-lines --ignore-space-change --ignore-blank-lines --width=200 $1 $2 | \
    awk 'NR==1{print} NR>1 && /[^a-zA-Z0-9]>[^a-zA-Z0-9]/ {print}'; \
    }
djJSON() { f_getJSON http://0.0.0.0/api_view/$1/?format=json; }
dl_unzip() { wget $1; tar -xzvf $1; }
edit_bash_prof() { $EDITOR "$HOME_ENV/$SHELL_CONFIG"; source_bash; }
edit_bash_share() { $EDITOR $HOME_ENV/.scripts/.alias_shared; source_bash; }
edit_linux_share() { $EDITOR $HOME_ENV/.scripts/.alias_linux; source_bash; }
edit_this_bash() { $EDITOR $SERV_HOME/$ALIAS; source_bash; }
f_find_file() { sudo find -H -s $1 -type f -iregex "$2"; }
f_find_file_exec() { sudo find -H -s $1 -type f -iregex '$2' -exec $3 '{}' ; }
f_find_folder() { sudo find -H -s $1 -type d -iregex "$2"; }
f_find_in_files() { sudo find $1 -type f | xargs grep -iE "$2"; }
f_getJSON() { curl -H 'Accept: application/json; indent=4' $1; }
f_sencha_build() { cd $APORO/static/sencha; sudo sencha app build production; }
gdiff() { git diff $@ | cdiff -s -w 110; }
jq_merge() { jq -sRcj ' [ splits("\n")? | split(":") as $i | { ($i[0]?) : ( $i[1] | sub("^(\\s)+"; ""; "x") ) } ]' | jq -cj 'add'; }
newalias_here() { echo "alias "$1 >> $SERV_HOME/$ALIAS; source_bash; }
newalias_linux() { echo "alias "$1 >> $HOME_ENV/.scripts/.alias_linux; pull_shared_scripts; source_bash; }
newalias_shared() { echo "alias "$1 >> $HOME_ENV/.scripts/.alias_shared; pull_shared_scripts; source_bash; }
pyprofileread() { python -m line_profiler $1.lprof; }
pyprofilewrite() { kernprof.py -l $1; }
RD() { cd $BD/RD/src; python seamless.py; }
RDt() { cd $BD/RD/src; python seamless_test.py; }
retar() { tar -zcvf $1 $2; }
source_bash() { _orig=`pwd`; source $HOME_ENV/$SHELL_CONFIG; cd $_orig; }

build_script_env_f() {
    FILE="$HOME_ENV/.scripts/script_env";
    env | sort | sed -r 's/^([^=]+)=(.*)$/\1="\2"/g' > $FILE;
    alias | sed -r 's/^(.*)$/alias \1/g' >> $FILE; \
    }
alias build_script_env='make_script_env_f'

alias AP_android='cd $APORO/static/sencha/phonegap/platforms/android/'
alias AP_phonegap_build_android='AP_android; sudo phonegap build android --release;'
alias AP_sencha='cd $APORO/static/sencha/'
alias AP_sencha_build='AP_sencha; sudo sencha app build package;'
alias assign_help='echo "assign some_variable < <(some code)"'
alias BD_env='cd $BD; source ENV/bin/activate'
alias cde='cde_f'
alias chmod_num='stat -c "%a"'
alias close_tcp='fuser -k -n tcp'
alias cmd='compgen -a | grep'
alias colordiff='colordiff --minimal --strip-trailing-cr --text --ignore-blank-lines --ignore-space-change --ignore-all-space --ignore-tab-expansion --ignore-trailing-space --suppress-common-lines --side-by-side'
alias columns='column -t | tr -s " "'
alias convert_pdf='pdftohtml -i -c -xml'
alias countF='ls | wc -l'
alias cy_build='cd $BD/RD/src/cython_exts/; python cy-build.py build_ext -i;'
alias cy_clean='cd $BD/RD/src/cython_exts/; sudo python cy-build.py clean;'
alias cy_folder='cd $BD/RD/src/cython_exts/;'
alias cy_help='cd $BD/RD/src/cython_exts/; python cy-build.py --help-commands;'
alias dir_size='du -sh'
alias ec2="ssh -i $HOME_ENV/.ssh/grp1.pem ec2-user@ec2-54-164-189-68.compute-1.amazonaws.com -p 10101"
alias ec2_pg_tunnel='ssh ub3 -L 9088:localhost:8800 -N &'
alias ec2_reboot='aws ec2 reboot-instances --instance-ids i-8206d068'
alias egrep='egrep -i --color=auto'
alias fgrep='fgrep -i --color=auto'
alias find_file='f_find_file'
alias find_folder='f_find_folder'
alias function_names='compgen -A function | sort'
alias get_tty='tty | sed -e "s/.*tty\(.*\)/\1/"'
alias git_sencha='echo "admin" | sudo git clone https://github.com/sethc23/aporo.git -b sencha $HOME_ENV/django/Dropbox/aporo/static/sencha'
alias grep='grep -i --color=auto'
alias grep_folder='grep -r "$1" *'
alias grok_app='ngrok -hostname app.aporodelivery.com 80'
alias grok_mysql='ngrok -proto tcp 3306'
alias grok_printer='ngrok -hostname printer.aporodelivery.com 80'
alias hist_cmds="history | awk '{\$1=\$2=\$3=\"\";print}' | sed 's/^   //'"
alias JSON='f_getJSON'
alias l-test="printf 'package.loaded.tmp=nil\nt=require\"tmp\"\nt.test()' | luap --"
alias locate='locate -i'
alias locate_info='locate -S'
alias locate_update='sudo /usr/libexec/locate.updatedb'
alias ls='ls --color --almost-all --classify --human-readable --ignore-backups --format=verbose --indicator-style=file-type --indicator-style=slash'
#alias ls='ls --almost-all --human-readable --ignore-backups --format=verbose --indicator-style=file-type --indicator-style=slash | LC_COLLATE=C sort -k9,9 --ignore-case'
alias mnt='scr_ed; ./System_Control.py servers mnt'
alias mnt_EXT_HD='mkdir -p /Volumes/EXT_HD; $SSHFS ub1:/Volumes/EXT_HD /Volumes/EXT_HD -o ConnectTimeout=5'
alias mysql_cmd='mysql -uroot -pDelivery100%'
alias mysql_config1='echo "money" | sudo emacs /opt/local/etc/mysql55/macports-default.cnf'
alias mysql_config2='echo "money" | sudo emacs /opt/local/etc/mysql55/my.cnf'
alias pb='pastebincl -n'
alias pip_install='pip install --upgrade --allow-all-external --allow-unverified basemap'
alias pip_update='$HOME_ENV/.scripts/update_pip.sh'
alias pip_upgrade='pip install -U pip'
alias ports_listen='sudo lsof -n -i -P | grep LISTEN'
alias ports_listen_2='sudo netstat -ltnp'
alias ports_listen_3='nettop'
alias ports_sockets='netstat -lx'
alias ports_ssh='lsof -i tcp | grep ^ssh'
alias ps-threads-full='pstree'
alias ps='ps -ax -o %cpu,%mem,start,etime,user,group,ppid,pid,tty,comm,args'
alias pull_shared_scripts='pull_shared_scripts'
alias push_shared_scripts='push_shared_scripts'
alias push_ssh_config='mnt; cp -R $HOME_ENV/.ssh/config /Volumes/mb/Users/admin/.ssh/; cp -R $HOME_ENV/.ssh/config /Volumes/ubuntu/home/ubuntu/.ssh/'
alias pydoc='python -m pydoc'
alias pyprofileread='pyprofileread'
alias pyprofilewrite='pyprofilewrite'
alias RD_e='cd $BD/RD/src'
alias RDt='RDt'
alias redis_config='sudo emacs /opt/local/etc/redis.conf'
alias redis_kill='pkill -f redis-server'
alias redis_run='redis-server /opt/local/etc/redis.conf'
alias restart='sudo shutdown -r now'
alias retar_help='echo retar archive.tar.gz directory/'
alias rsync_all='python $BD/rsync_cmds.py all'
alias rsync_test='python $BD/rsync_cmds.py test'
alias rt_='ssh cisco'
alias rt_nat='rt_ "iptables -t nat -L -v" 2> /dev/null'
alias rt_ps='rt_ "ps" 2> /dev/null'
alias rt_reboot='rt_ reboot'
alias rt_tbl='rt_ "iptables -L -v" 2> /dev/null'
alias scr_d='scr_ed'
alias scr_ed='scr_env; cd $HOME_ENV/.scripts'
alias scr_env='source $HOME_ENV/.scripts/ENV/bin/activate'
alias scr_sync='$HOME_ENV/.scripts/sync_scripts.bash'
alias ssh_config='emacs $HOME_ENV/.ssh/config; push_ssh_config'

sn4_ar_msg() { curl "http://autoremotejoaomgcd.appspot.com/sendmessage?key=APA91bG9W7n3uAWVND-jaRRbh0muYlx6znEJgUUFrMnRxGuagYMmRuTJ2OONeHD6ibkj1_nRgM8s7ah1WyDbFAMHX2Rf28dNdzpRHMUJUKPPvseoWDI_pHX2lHaEeoBsD7KZoyG4mfUwgT_Yl1CyHIVpy1Jx9zCrdw&message=$1"; }
alias sn4_ar_key='echo "APA91bG9W7n3uAWVND-jaRRbh0muYlx6znEJgUUFrMnRxGuagYMmRuTJ2OONeHD6ibkj1_nRgM8s7ah1WyDbFAMHX2Rf28dNdzpRHMUJUKPPvseoWDI_pHX2lHaEeoBsD7KZoyG4mfUwgT_Yl1CyHIVpy1Jx9zCrdw"'
sn4_backup() { \
    sn4_ar_msg ssh_droid_start > /dev/null 2>&1;
    RES=$($HOME_ENV/.scripts/ENV/bin/celery --workdir=$HOME_ENV/.scripts/worker --app=sys_serv \
    call --queue=sys_serv_tasks sys_serv_tasks.sn4_backup --args='[]' \
    --countdown=20 | xargs -I '{}' printf 'sn4_backup [%s %s] expecting git task ID -- %s\n' $(date +%Y-%m-%d\ %H:%M:%S) {});
    echo $RES >> /var/sockets/supervisor_relay.log;
    echo 'OK';
}
alias sn4_ssh_droid_start='curl "https://autoremotejoaomgcd.appspot.com/sendmessage?key=APA91bG9W7n3uAWVND-jaRRbh0muYlx6znEJgUUFrMnRxGuagYMmRuTJ2OONeHD6ibkj1_nRgM8s7ah1WyDbFAMHX2Rf28dNdzpRHMUJUKPPvseoWDI_pHX2lHaEeoBsD7KZoyG4mfUwgT_Yl1CyHIVpy1Jx9zCrdw&message=ssh_droid%20start"'
alias sn4_ssh_droid_stop='curl "https://autoremotejoaomgcd.appspot.com/sendmessage?key=APA91bG9W7n3uAWVND-jaRRbh0muYlx6znEJgUUFrMnRxGuagYMmRuTJ2OONeHD6ibkj1_nRgM8s7ah1WyDbFAMHX2Rf28dNdzpRHMUJUKPPvseoWDI_pHX2lHaEeoBsD7KZoyG4mfUwgT_Yl1CyHIVpy1Jx9zCrdw&message=ssh_droid%20stop"'
alias sn4_teamviewer_start='adb shell monkey -p com.teamviewer.quicksupport.market -c android.intent.category.LAUNCHER 1'
alias sn4_copy_screen_png_here='adb shell screencap -p /sdcard/screen.png && adb pull /sdcard/screen.png && adb shell rm /sdcard/screen.png'

alias test_nginx_socket='socat - UNIX-CLIENT:/var/log/nginx.sock'
alias to_log='syslog -s -l error -k Message'
alias topcpu='ps -ero pid=PID,%cpu=CPU,%mem=MEM,comm=CMD | head -15'
alias topmem='ps -emo pid=PID,%cpu=CPU,%mem=MEM,comm=CMD | head -15'
alias umnt='sudo umount -f /Volumes/'
alias untar='tar -zxvf'
alias z_local="emacs $SH/local_config/shell/.shell_local"
alias z_omz="emacs $HOME_ENV/.scripts/shell_env/zsh/.z_OMZ"
alias z_source="source $HOME_ENV/.scripts/shell_env/zsh/.z_OMZ; source $HOME_ENV/.scripts/shell_env/_base"




# --------------------------------------------------------------------------
#
#   TODO
#
# --------------------------------------------------------------------------

#function g-RESTORE_LOCAL_F() { \
#    cd $HOME_ENV/$SERVER/local_config/ \
#    ln -s $HOME_ENV/.git/.gitignore ./; \
#   ln -s $HOME_ENV/.git/.gitignore_global ./; \
#   ln -s $HOME_ENV/$SERVER/local_config/.bashrc ./ ; \
#   ln -s $HOME_ENV/$SERVER/local_config/.iterm2 ./ ; \
#   ln -s $HOME_ENV/$SERVER/local_config/.profile ./ ; \
#   ln -s $HOME_ENV/$SERVER/local_config/.bash_profile ./ ;}

# Out Specific Lines
# sed -n '20,40p' file_name
# awk 'FNR>=20 && FNR<=40' file_name

# history | sed -e 's/^[ \t]*//' | sort -u -k4 | sort -k1
# need to standardize column separation and re-split --> see alias 'columns'

