#!/bin/zsh

# source $HOME_ENV/.profile
# source $HOME_ENV/.scripts/shell_env/_base

case $- in
    *i*);;
    *) return ;;
esac

source $HOME_ENV/.scripts/shell_env/shell/zsh/_env 
source $HOME_ENV/.shell_local

