#!/bin/bash

if [[ -n "$SUDO_USER" ]]; then
    export HOME_ENV=$(eval echo ~$SUDO_USER)
else
    export HOME_ENV=$(eval echo ~$USER)
fi

source $HOME_ENV/.profile
source $HOME_ENV/.scripts/shell_env/_base

case $- in
    *i*) ;;
    *) return;;
esac

source $HOME_ENV/.scripts/shell_env/zsh/_env
source ~/.shell_local

autoload bashcompinit
bashcompinit
for i in `env find $HOME_ENV/.scripts/shell_env/zsh/completers -maxdepth 1 -type f`; do source $i; done


source $HOME_ENV/.scripts/shell_env/zsh/completers/py-argcomplete.sh
# eval "$(register-python-argcomplete /home/ub2/.scripts/System_Control.py)"
