#!/bin/zsh

case $- in
    *i*) ;;
      *) source ~/.profile && source ~/.scripts/shell_env/_base && return;;
esac

source ~/.profile
source ~/.scripts/shell_env/zsh/_env
source ~/.scripts/shell_env/_base
source $SH/local_config/shell/.shell_local


for i in `env find ~/.scripts/shell_env/zsh/completers -maxdepth 1 -type f`; do source $i; done
