#!env zsh

ib_e() { cd $IPY; source ENV/bin/activate; }
ib_qt_ub2() { sudo $IPY/ENV/bin/ipython qtconsole --existing /Volumes/ub2/home/ub2/.ipython/profile_default/security/kernel-$1.json;}

alias ib='$IPY/ENV/bin/ipython console --profile=nbserver --matplotlib=qt4 --pprint --autoindent --color-info --colors=linux --confirm-exit;'
alias ib_config='f_sudo_textedit ~/.ipython/profile_nbserver/ipython_config.py'
alias ib_console='$SERV_HOME/ipython/ENV/bin/ipython console --profile=nbserver --pprint --autoindent --color-info --colors=linux --confirm-exit;'
ib_console_existing() { $SERV_HOME/ipython/ENV/bin/ipython console --profile=nbserver --pprint --autoindent \
    --color-info --colors=linux --confirm-exit \
    --existing $SERV_HOME/ipython/config/.ipython/profile_default/security/$1; }
alias ib_js='f_sudo_xcode ~/.ipython/profile_nbserver/static/custom/custom.js'
alias ib_js_folder='open $HOME/.ipython/profile_nbserver/static/custom/'
alias ib_BD='cd $BD; source $SERV_HOME/ipython/ENV/bin/activate; ipython'
alias ib_scr='scr_ed; ipython'
alias ib_libs='ls $IPY/ENV/lib/python2.7/site-packages/; echo $IPY/ENV/lib/python2.7/site-packages/; echo "/usr/lib/python2.7/dist-packages/"; echo "/usr/local/lib/python2.7/dist-packages"'

alias jupyter_nbconvert='jupyter-nbconvert --to=notebook --nbformat=3 --inplace $SERV_HOME/ipython/notebooks/'

alias svc_ipy_enable='sudo systemctl daemon-reload; sudo systemctl enable $SERV_HOME/ipy_jupyter/jupyter/jupyter-notebook.service 2> /dev/null;'
alias svc_ipy_disable='sudo systemctl disable jupyter-notebook.service; sudo systemctl daemon-reload'
alias svc_ipy_start='sudo systemctl start jupyter-notebook.service'
alias svc_ipy_restart='sudo systemctl restart jupyter-notebook.service'
alias svc_ipy_stop='sudo systemctl stop jupyter-notebook.service'
alias svc_ipy_status='sudo systemctl status jupyter-notebook.service'

alias ib_test='jupyter-notebook \
    --config=/home/ub2/.jupyter/jupyter_notebook_config.py \
    --no-browser --debug'