#!env zsh

function m_proxy_eth() { \
    ipt-flush; \
    ipt-nat-flush; \
    sudo iptables -t nat -I OUTPUT -o eth0 -p tcp -m owner \! --uid-owner mitmproxy --dport 80 -j REDIRECT --to-port 10052; \
    sudo iptables -t nat -I OUTPUT -o eth0 -p tcp -m owner \! --uid-owner mitmproxy --dport 443 -j REDIRECT --to-port 10052; \
    sudo -u mitmproxy -c "source /home/ub2/GIT_REPOS/mitmproxy/ENV/bin/activate && /home/ub2/GIT_REPOS/mitmproxy/ENV/bin/mitmweb --transparent -wport=11152 --wiface=eth0 --wfile=mitm_res.out --wdebug --port 10052" && sudo iptables -t nat -F;
}

function m_proxy_tun() { \
    ipt-flush; \
    ipt-nat-flush; \
    sudo iptables -t nat -I OUTPUT 1 -o tun0 -m owner \! --uid-owner mitmproxy -p tcp --dport 80 -j REDIRECT --to-port 10052; \
    sudo iptables -t nat -I OUTPUT 1 -o tun0 -m owner \! --uid-owner mitmproxy -p tcp --dport 443 -j REDIRECT --to-port 10052; \
    #sudo -u mitmproxy mitmproxy --transparent --port 10052 --eventlog --intercept '.*' && sudo iptables -t nat -F; \
    sudo -u mitmproxy mitmweb --transparent -wport=11152 --wiface=eth0 --wfile=mitm_res.out --wdebug --port 10052 && sudo iptables -t nat -F;
}