#!/bin/zsh

alias svc_pgsql_disable='sudo systemctl disable postgresql@9.5-main.service'
alias svc_pgsql_enable='sudo systemctl enable postgresql@9.5-main.service'
alias svc_pgsql_start='sudo systemctl start postgresql@9.5-main.service'
alias svc_pgsql_stop='sudo systemctl stop postgresql@9.5-main.service'
alias svc_pgsql_restart='sudo systemctl restart postgresql@9.5-main.service'
alias svc_pgsql_status='sudo systemctl status postgresql@9.5-main.service'
alias svc_pgsql_debug='sudo /usr/local/sbin/rsyslogd -d -f /etc/rsyslog.d/debug.conf -n'


#alias pg_PUSH_CONFIG='sudo cp -R $SERV_HOME/pgsql93/postgresql93 /etc/rc.d/init.d/'
#alias pg_RESET='sudo chkconfig postgresql93 reset'
#alias pg_SHUTDOWN='sudo su postgres -c "pg_ctl stop -D /home/postgres/pgsql93/defaultdb -m smart"'

alias pg_tmp_start_with_echo="sudo su postgres -c '/usr/lib/postgresql/9.5/bin/pg_ctl start -D $PG_DATA_DIR -l /tmp/pgsql -o\" -i -E\"'"
function pg_tmp_start_with_echo_and_debug() {     \
    sudo su postgres -c "/usr/lib/postgresql/9.5/bin/postgres -D /var/lib/postgresql/9.5/main -i -E -c log_destination='stderr' -c logging_collector='on' -c log_directory='/tmp/pgsql' -c log_statement='all' -c log_min_messages='debug' -c log_min_duration_statement=0"; }
alias pg_tmp_start_with_echo_and_debug='pg_tmp_start_with_echo_and_debug'
alias pg_tmp_start="sudo su postgres -c '/usr/lib/postgresql/9.5/bin/pg_ctl start -D $PG_DATA_DIR -o\" -i\"'"
alias pg_tmp_stop="sudo su postgres -c '/usr/lib/postgresql/9.5/bin/pg_ctl stop -m fast -D $PG_DATA_DIR -o\" \"'"

alias psql94='sudo su postgres -c "psql --host=0.0.0.0 --port=8800 --username=postgres"'
alias psql95='sudo su postgres -c "psql --host=0.0.0.0 --port=8801 --username=postgres"'

function psql_c() { sudo su postgres -c "psql --host=0.0.0.0 --port=8800 --username=postgres -c '$1'"; }
function pg_load_dump_file() { \
    OUT_FILE_NAME=echo "$1" | sed -r 's/(.*)\/([^/]*)(\.sql)$/\2_OUT/'; \
    echo $OUT_FILE_NAME;}
    #DB_NAME=echo $1 | sed -r 's/(.*)\/([^_]*)_([^_]*)([^/]*)(\.sql)$/\3/'; \
    #sudo su postgres -c 'psql --host=0.0.0.0 --port=8800 --username=postgres -c "create database $DB_NAME;"'; \
    #sudo su postgres -c "psql --host=0.0.0.0 --port=8800 --username=postgres --dbname=$DB_NAME -f $1" >> $OUT_FILE_NAME 2>&1; \
    #unset OUT_FILE_NAME DB_NAME;}
export PG_DATA_DIR=/var/lib/postgresql/9.5/main
alias _pg_reload='sudo su postgres -c "/usr/lib/postgresql/9.5/bin/pg_ctl reload -D $PG_DATA_DIR"'

alias _pg_restart_smart='sudo su postgres -c "source $SERV_HOME/pgsql/ENV/bin/activate; /usr/lib/postgresql/9.5/bin/pg_ctl restart -w -D $PG_DATA_DIR -m smart"'
alias _pg_restart_fast='sudo su postgres -c "source $SERV_HOME/pgsql/ENV/bin/activate; /usr/lib/postgresql/9.5/bin/pg_ctl restart -w -D $PG_DATA_DIR -m fast"'
alias _pg_restart_immediate='sudo su postgres -c "source $SERV_HOME/pgsql/ENV/bin/activate; /usr/lib/postgresql/9.5/bin/pg_ctl restart -w -D $PG_DATA_DIR -m immediate"'

#alias _pg_restart_smart='sudo su postgres -c "/usr/lib/postgresql/9.5/bin/pg_ctl restart -w -D $PG_DATA_DIR -m smart"'
#alias _pg_restart_fast='sudo su postgres -c "/usr/lib/postgresql/9.5/bin/pg_ctl restart -w -D $PG_DATA_DIR -m fast"'
#alias _pg_restart_fast='sudo su postgres -c "source $SERV_HOME/ipython/ENV/bin/activate; /usr/lib/postgresql/9.5/bin/pg_ctl restart -w -D $PG_DATA_DIR -m fast"'
#alias _pg_restart_immediate='sudo su postgres -c "source $SERV_HOME/ipython/ENV/bin/activate; /usr/lib/postgresql/9.5/bin/pg_ctl restart -w -D $PG_DATA_DIR -m immediate"'
alias _pg_restart_fast_core='sudo su postgres -c "/usr/lib/postgresql/9.5/bin/pg_ctl restart -c -w -D $PG_DATA_DIR -m fast"'
alias _pg_configs='psql_c "show all;"'
alias _pg_configs_edit='semacs /etc/postgresql/9.5/main/postgresql.conf'
#alias _pg_pid="pid=$(ps -ef | grep '/usr/lib/postgresql/9.5/bin/postgres' | grep -E '^postgres' | sed 's/^postgres //g' | sed -E 's/([^[0-9]]*)([0-9]+)(.*)/\2/')"


function pgsql_tail_info_logger() { :> /tmp/tmplog; tail -n 0 -f /tmp/tmplog | while read line; \
    do echo $line | grep '^[[:alnum:]]' | grep -e '- INFO - LOG:' | sed -ur 's/^(.*)(- INFO - LOG: )(.*)$/\3/g'; done; }