#!/bin/zsh


alias rq_status='sudo rabbitmqctl status'
alias rq_cel_run='cel_env; celery -A --app=sync_app --workdir=$SERV_HOME/aprinto/celery worker --loglevel=info'
alias rq_cel_purge='cel_env; celery purge -f --broker=amqp://ub2:mq_money@localhost:5672//'
alias rq_start='sudo service rabbitmq-server start'
alias rq_stop='sudo service rabbitmq-server stop'
alias rq_restart='sudo service rabbitmq-server restart'
alias rq_config='sudo emacs /etc/rabbitmq/rabbitmq.config'
alias rq_q='sudo rabbitmqctl list_queues'
alias rq_x='sudo rabbitmqctl list_exchanges'
alias rq_b='sudo rabbitmqctl list_bindings'
alias rq_c='sudo rabbitmqctl list_consumers'
alias rq_r='sudo rabbitmqctl report'
alias rq_tail_start_err='sudo tail -n 50 -f /var/log/rabbitmq/startup_err'
alias rq_remaining='sudo rabbitmqctl list_queues name messages messages_ready messages_unacknowledged'