#!/bin/zsh

function sv_push_config() { sl_push_config; sudo $SERV_HOME/supervisor_root/push_sv_config_root.bash; }
alias sv_reset='sv_push_config && sv_ctl reread && sv_ctl update'
alias sv_s='sv_ctl status'
alias sv_tail='sudo tail -n 100 -f /var/log/syslogs/supervisor.log'
alias sv_ctl='sudo supervisorctl -s unix:///var/sockets/supervisor_root.sock'
alias sv_update='sudo supervisorctl -s unix:///var/sockets/supervisor_root.sock reread && sudo supervisorctl -s unix:///var/sockets/supervisor_root.sock update'
alias sv_load='sv_push_config; sudo systemctl start supervisord.service'
alias sv_unload='sudo systemctl stop supervisord.service'
alias sv_reload='sv_push_config; sudo systemctl daemon-reload; sudo systemctl restart supervisord.service'