#!/bin/bash

if [[ -n "$SUDO_USER" ]]; then
    export HOME_ENV=$(eval echo ~$SUDO_USER)
else
    export HOME_ENV=$(eval echo ~$USER)
fi

case $- in
    *i*) ;;
      *) source $HOME_ENV/.profile && source $HOME_ENV/.scripts/shell_env/_base && return;;
esac


source $HOME_ENV/.profile
source $HOME_ENV/.scripts/shell_env/_base
source ~/.shell_local

if [[ -n "$BASH_VERSION" ]]; then
    DIR="$HOME_ENV/.scripts/shell_env/bash/completers"
    for i in `env find $DIR -maxdepth 1 -type f`; do source $i; done
fi
